"""Core data contracts, protocol invariants, provenance, and evaluation metrics."""

from core.contracts import (
    SCHEMA_VERSION,
    AdapterEntry,
    AdapterSpec,
    AlignmentCheckpointMetadata,
    Component,
    EvaluationRecord,
    OODEvaluationRecord,
    RunManifest,
    TaskEvidence,
)
from core.metrics import (
    CorrelationEstimate,
    average_forgetting,
    average_success_rate,
    bootstrap_correlation,
    continual_learning_metrics,
    forward_transfer,
    negative_backward_transfer,
    normalized_negative_backward_transfer,
    recovery_step_ratio,
)
from core.protocol import (
    REQUIRED_SUITES,
    PopulationRun,
    expand_population_runs,
    load_yaml,
    publication_folds,
    resolve_config_path,
    validate_reference_tasks,
    validate_research_config,
)
from core.provenance import (
    capture_environment,
    capture_hardware,
    git_state,
    sha256_array_tree,
    sha256_file,
    write_manifest_atomic,
)
from core.records import (
    append_evaluation_record,
    append_ood_evaluation_record,
    export_evaluation_parquet,
    load_evaluation_records,
    load_ood_evaluation_records,
    records_to_success_matrix,
)
from core.sequential import StageUpdate, run_sequential_protocol

__all__ = [
    "REQUIRED_SUITES",
    "SCHEMA_VERSION",
    "AdapterEntry",
    "AdapterSpec",
    "AlignmentCheckpointMetadata",
    "Component",
    "CorrelationEstimate",
    "EvaluationRecord",
    "OODEvaluationRecord",
    "PopulationRun",
    "RunManifest",
    "StageUpdate",
    "TaskEvidence",
    "append_evaluation_record",
    "append_ood_evaluation_record",
    "average_forgetting",
    "average_success_rate",
    "bootstrap_correlation",
    "capture_environment",
    "capture_hardware",
    "continual_learning_metrics",
    "expand_population_runs",
    "export_evaluation_parquet",
    "forward_transfer",
    "git_state",
    "load_evaluation_records",
    "load_ood_evaluation_records",
    "load_yaml",
    "negative_backward_transfer",
    "normalized_negative_backward_transfer",
    "publication_folds",
    "records_to_success_matrix",
    "recovery_step_ratio",
    "resolve_config_path",
    "run_sequential_protocol",
    "sha256_array_tree",
    "sha256_file",
    "validate_reference_tasks",
    "validate_research_config",
    "write_manifest_atomic",
]
